spring:
  application:
    name: product-service
  datasource:
    username: postgres
    password: database09
    url: jdbc:postgresql://localhost:5432/feign_db
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8082